name = "Omics"
uuid = "55404059-57b2-473d-9cce-582834f19b54"
authors = ["KwatMDPhD"]
version = "0.6.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
CSV = "0.10.14"
Clustering = "0.15.7"
CodecZlib = "0.7.6"
ColorSchemes = "3.26.0"
Colors = "0.12.11"
DataFrames = "1.7.0"
Dates = "1.11.0"
Distances = "0.10.11"
Distributions = "0.25.112"
GLM = "1.9.0"
JSON = "0.21.4"
KernelDensity = "0.6.9"
Mmap = "1.11.0"
MultipleTesting = "0.6.0"
OrderedCollections = "1.6.3"
Printf = "1.11.0"
Random = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.3"
TOML = "1.0.3"
Test = "1.11.0"
XLSX = "0.10.4"
